---
- name: Ejecutar consulta PostgreSQL en servidor Windows por PowerShell
  hosts: all
  gather_facts: false

  tasks:
    - name: Copiar script PowerShell al servidor remoto
      ansible.windows.win_copy:
        src: scripts/query_postgres.ps1
        dest: C:\Users\WIN2019\Documents\query_postgres.ps1

    - name: Ejecutar script PowerShell para consultar PostgreSQL
      ansible.windows.win_powershell:
        script: |
          C:\Users\WIN2019\Documents\query_postgres.ps1
      register: postgres_query_output
      args:
        executable: powershell.exe

    - name: Mostrar resultado de la consulta PostgreSQL
      ansible.builtin.debug:
        msg: "{{ postgres_query_output.output | join('\n') }}"
      when: postgres_query_output.output is defined and postgres_query_output.output | length > 0

    - name: Mostrar errores si los hay
      ansible.builtin.debug:
        msg: "{{ postgres_query_output.stderr_lines | join('\n') }}"
      when: postgres_query_output.stderr_lines is defined and postgres_query_output.stderr_lines | length > 0
